### PR TITLE
Logo refresh

### PR DESCRIPTION
**Pull request by bheesham**
Jira: [IAM-1513](https://mozilla-hub.atlassian.net/browse/IAM-1513)

---

Screenshot 2024-12-09 at 10 57 16

### CODE REVIEW

**Comment by bheesham** [comment]
For future wanderers: I couldn't get this working natively, so I ran stuff using Docker.

Something along these lines:

```
docker run -v "$(PWD):/src" -w /src --entrypoint npm -it node:14 install
docker run -v "$(PWD):/src" -w /src -p 3000:3000 --entrypoint npm -it node:14 run watch
# Open your browser and go to http://localhost:3000/
```

I'm open to adding this stuff to the documentation, but before that I'd like trying to upgrade deps, etc, etc and get it working without a workaround.

**Comment by dividehex** [comment]
Nice work.  The "Mozilla" word logo also needs to be updated.  see https://brand.mozilla.com for guide lines and image assets.

**Comment by bheesham** [comment]
> Nice work. The "Mozilla" word logo also needs to be updated. see https://brand.mozilla.com for guide lines and image assets.

Done! I updated the screenshot in the PR description to match.

**Review by dividehex — APPROVED** [review]
🎯 Approved

**Pull request merged**
